---
- name: test group priority
  hosts: prio10:prio5
  gather_facts: no
  tasks:
    - debug: msg="do some stuff"

- name: test group priority inheritance
  hosts: hardware:networking
  gather_facts: no
  tasks:
    - debug: msg="do some stuff"